### ISSUE TITLE
FEATURE REQUEST: use qsub -N to name job according to stage/filename

### ISSUE THREAD

**Issue by gdevenyi** [ssadedin/bpipe#128]
Right now, when bpipe jobs are submitted to SGE, all of them are named "cmd.sh" which is the file bpipe generates hidden away in .bpipe. It would be nice for monitoring the process of the bpipe (and the state of the cluster) to submit a name to the job using "qsub -N jobnamegoeshere". An ideal name would be some combination of the current stage and the input file(s).

**Comment by gdevenyi** [comment]
This could also be configured by using
```
#$ -N jobname
```
Added to the top of cmd.sh

**Comment by ssadedin** [comment]
This is added in cf78c13 (will release as 0.9.8.7).

Thanks!

**Comment by gdevenyi** [comment]
Cheers, it works as expected! This has allowed me to aggregate the memory and walltime of my various stages and much refine my pipeline specification.
