### ISSUE TITLE
Groovy Syntax Reference?

### ISSUE THREAD

**Issue by gdevenyi** [ssadedin/bpipe#137]
I'd like to add some branching to my pipelines in the form of "if this variable is defined, do this, otherwise, do that". I already know how to define new branch variables, but since bpipe is a superset of groovy, can you suggest a good simple reference for groovy syntax to extend my pipeline?

**Comment by ssadedin** [comment]
Hi Gabriel,

I think this might be a good question to pose to the mailing list - would
you mind posting it there? I'll try to follow up promptly.

Cheers,

Simon

**Comment by gdevenyi** [comment]
Answered on mailing list
