### ISSUE TITLE
Stage variables when running multiple branches in parallel

### ISSUE THREAD

**Issue by danhalligan** [ssadedin/bpipe#146]
I'm not 100% sure this is a bug, but the behaviour seems odd to me. Essentially, it seems that variables defined within a stage from one branch can get overwritten by other branches. Minimal reproducible example below using bpipe 0.9.8.7

    # test.bpipe
    s1 = {
         outdir = branch.name
         exec "mkdir $outdir"
    }
    Bpipe.run { "%.txt" * [ s1 ] }

    # setup files and run pipeline
    > touch 1.txt 2.txt 3.txt && bpipe test.bpipe *.txt

When the above is run, my output commandlog.txt file is as follows:

    ####################################################################################################
    # Starting pipeline at Tue Jun 16 10:30:59 BST 2015
    # Input files:  [1.txt, 2.txt, 3.txt]
    # Output Log:  .bpipe/logs/19045.log
    # Stage s1 [1]
    # Stage s1 [3]
    # Stage s1 [2]
    mkdir 2
    mkdir 3
    mkdir 3
    # ################ Finished at Tue Jun 16 10:31:00 BST 2015 Duration = 0.933 seconds #################

Importantly, one of the mkdir commands is duplicated, presumably because the in stage variable outdir is shared between multiple branches? Is this the expected behaviour. If so, it would be great if you could let me know the best workaround for creating branch specific variables safely.

**Comment by gdevenyi** [comment]
Any branch-specific variables need to be prefixed with "branch" hence, your outdir needs to be branch.outdir otherwise other branches clobber it.

I recently had a infinite loop in bpipe due to not heeding this.

**Comment by danhalligan** [comment]
Thanks for the tip!

**Comment by zichner** [comment]
An alternative is to use the keyword "def" to indicate that a variable is local:
```
def outdir = branch.name
```

**Comment by gdevenyi** [comment]
@zichner I didn't see that in the documentation, where does this come from?

**Comment by zichner** [comment]
It is mentioned on the "old" Bpipe troubleshooting page:
https://code.google.com/p/bpipe/wiki/Troubleshooting

**Comment by ssadedin** [comment]
I've added an explicit note in the new documentation on variables:

http://docs.bpipe.org/Language/Variables/

For now I am closing this, but my longer term intention is to make new variables defined within pipeline stages NOT have global scope, as I think that will always be dangerous behavior and easy to do by accident even for experienced people.
