### ISSUE TITLE
Better support for environment modules

### ISSUE THREAD

**Issue by humburg** [ssadedin/bpipe#161]
I'm trying to set up bpipe for use on SGE (using 7266d7466c809e7642ba5e6a443249b412245b00). This now seems to work for the most part but I haven't managed to get environment modules to work properly (this seems related to #10). Ideally I would like to be able to specify the modules to use either in the pipeline config or for each pipeline module in some way. 

Initially I thought I could just add something like `exec "module load <module_name>"` as the first command to be executed for each module but unfortunately that doesn't work. As far as I can tell each `exec` is submitted as a separate job, so they don't share an environment. A construct like this works:

```
exec "module load <module_name> && command"
```
But that seems a bit clunky (and I think also prevents changes to resource requirements for `command`). A possible solution might be to create a single script for all `exec` statements in a block.

**Comment by gdevenyi** [comment]
I handle environment-modules support by using "-V" in my job scripts. So I load my modules before running bpipe, and jobs inherit the environment from the submitting terminal.

This has worked out well here.

**Comment by humburg** [comment]
Thanks @gdevenyi, that does indeed seem to work. I'm sure I tried that before but it may have been with the latest release rather than 7266d74. That seems like a sensible solution. My only suggestion would be to include `-V` by default in the template. Or are there any situations where you wouldn't want that?

**Comment by gdevenyi** [comment]
I got some pushback about -V in https://github.com/ssadedin/bpipe/issues/156

The new method of using "template" jobs in branch sge_fixes will allow users to modify their default job configuration a little better, this would be the place to add -V

**Comment by humburg** [comment]
Fair enough. Of course the template makes the defaults very flexible and editing the file is easy enough. Is there a way to tell bpipe where to look for this template? It seems like a good idea to keep a customised template separate from the default to avoid accidentally overwriting it when installing a new version (and different users/projects sharing the same installation may want to set different defaults).

**Comment by ssadedin** [comment]
I've pushed another change to the sge_fixes branch that lets you specify the template in your bpipe.config using a syntax like:

jobTemplate="mytemplate.sh"

It can also be a closure that will get evaluated at runtime.

**Comment by humburg** [comment]
That's great. Thanks!
