### ISSUE TITLE
Terminated jobs not removed from SGE queue

### ISSUE THREAD

**Issue by humburg** [ssadedin/bpipe#162]
It looks like terminating bpipe jobs that have been submitted to an SGE queue doesn't remove them from the queue (observed with 7266d74). I noticed this when I aborted a bpipe run shortly after it had started because I realised that I had set a parameter incorrectly. I then resubmitted the same jobs shortly afterwards and ended up with two sets of (almost) identical jobs running on the cluster.

The [code](https://github.com/ssadedin/bpipe/blob/sge_fixes/src/main/groovy/bpipe/executor/SgeCommandExecutor.groovy#L279-L312) suggests tha a `qdel` command should be issued together with a corresponding log entry but this doesn't appear to be the case. I terminated the jobs by quitting the bpipe process (with `Ctrl-C`) and answering "y" to the question whether or not the running pipeline job should be terminated. 

As I said, the result was that the jobs kept running and there was no entry in the log suggesting an attempt to delete them. Here is the tail of the corresponding log file:

```
bpipe.Forwarder [32]    INFO    |10:22:55 Scanning 1 / 1 files  
bpipe.Forwarder [32]    INFO    |10:22:55 Scanning 1 / 1 files  
bpipe.Forwarder [32]    INFO    |10:22:55 Scanning 1 / 1 files  
bpipe.Forwarder [32]    INFO    |10:22:55 Scanning 1 / 1 files  
bpipe.Concurrency       [1]     INFO    |10:22:56 Waiting for 2 parallel stages to complete (pool.active=2 pool.tasks=2) 
bpipe.Forwarder [32]    INFO    |10:22:57 Scanning 1 / 1 files  
bpipe.Forwarder [32]    INFO    |10:22:57 Scanning 1 / 1 files  
bpipe.Forwarder [32]    INFO    |10:22:57 Scanning 1 / 1 files  
bpipe.Forwarder [32]    INFO    |10:22:57 Scanning 1 / 1 files  
bpipe.Runner    [9]     INFO    |10:22:59 Deleting job file /home/username/.bpipedb/jobs/29465 
```

**Comment by ssadedin** [comment]
Thanks for reporting it. 

There's a possibly related issue currently which is that there is a race condition such that if Bpipe starts a job at exactly the same instant that the "stop" command hits (or the terminate from a Ctrl-C), it may miss the started job and leave it running. A second "bpipe stop" usually does the job in that case. It would be good to know if the second "bpipe stop" works in your case?

**Comment by ssadedin** [comment]
Ok, it was much simpler than that. I have pushed what I hope is a fix to the sge_fixes branch.

@humburg  - would be great if you could give that a test.

**Comment by humburg** [comment]
@ssadedin Thanks for getting this sorted out so quickly. I can confirm that jobs now get deleted from the queue. However, I also get errors of the form 

```
Failed to stop command: bpipe.executor.SgeCommandExecutor@50c8f54c.

    SGE failed to stop command 31, returned exit code 1 from command line: qdel Your job 3984751 ("fastqc") has been submitted

The job may already be stopped; use 'bpipe cleancommands' to clear old commands.
```
Despite what the error message says the deletion seems to work fine. The part of the error that says `qdel Your job 3984751 ("fastqc") has been submitted` that the job ID isn't captured properly. 

This looks like the standard message printed by qsub but the SGE template does contain the `-terse` option, which should suppress this in favour of simply printing the job ID. Looks like that may not be working for some reason.

**Comment by humburg** [comment]
I had a closer look at what is going on with the `-terse` option. Some additional clues are below but I don't think I really understand what is going on here.

I used the default SGE template, which has

```
#\$ -wd ${bpipe.Runner.canonicalRunDirectory}
#\$ -N "$name"
#\$ -terse
#\$ -o $jobDir/$CMD_OUT_FILENAME
#\$ -e $jobDir/$CMD_ERR_FILENAME
#\$ -notify
${additional_options}
```
In my bpipe.config for the project I have

```
executor = "sge"
procs = "smp 1"
sge_request_options = "-l h_vmem=2G,mem_requested=2G -V -S /bin/bash"
```

The script generated from the template then contains the following:

```
#$ -wd /share/ClusterScratch/username/projectname
#$ -N "fastqc"
#$ -terse
#$ -o .bpipe/commandtmp/31/cmd.out
#$ -e .bpipe/commandtmp/31/cmd.err
#$ -notify
#$ -pe smp 1
```
And according to the log file the command used to submit the job is

```
qsub -V -notify -l h_vmem=2G,mem_requested=2G -V -S /bin/bash .bpipe/comm
andtmp/31/cmd.sh
```
The log file also says `Started command with id Your job 3984751 ("fastqc") has been submitted`,
which again suggests that `-terse` was ignored. Interestingly, this also shows that the `-N` option taking effect (and the indicated output files are used as well). It also seems that `-V` and `-notify` are hard coded (but for some reason I had issues earlier with the environment not being exported when I didn't include `-V` explicitly (see discussion of #161)). I have confirmed that `-terse` works as expected when I use it on the command-line.

**Comment by ssadedin** [comment]
Is it the case perhaps that -terse is not supported inside the job script but must be supplied via command line? In that case it might work if you put it into sge_request_options?

**Comment by humburg** [comment]
Of course you are right, including it in *sge_request_options* works. This might suggest that options that are critical for bpipe to work (`-terse` and `-notify`?) should be hardcoded as part of the qsub command and everything else should be left to the template and config file.

**Comment by ssadedin** [comment]
I think -notify is indeed included on the command, it probably doesn't need to be in the template. From what I can see the -terse was always in the job script. It makes me think there must be something version dependent there, because it definitely seems to work for me from the job script. 

I have pushed another change to place -terse into the command. For now I left both -notify and -terse in the job script because it doesn't seem to do any harm, and who knows, perhaps there is some version of SGE out there that needs them in the job script.

**Comment by humburg** [comment]
Works great now. Thanks again.

**Comment by ssadedin** [comment]
Thanks for your help!
