### ISSUE TITLE
Feature request: embedded script support

### ISSUE THREAD

**Issue by gdevenyi** [ssadedin/bpipe#174]
I'd like to be able to write a script block in bpipe that executes sequentially.

Motivation:
I have a stage that produces a quality-control image, the way that I do it, I produce three different views in a temporary directory, concatenate them, and return the result.

Right now, I can be clever and write some bash that uses ";" or "&&" to make it a single command, but it would be helpful to allow embedded bash scripts.

**Comment by gdevenyi** [comment]
Example:

```
n4correct = {
    branch.name = "${branch.name}.n4correct"
    //Runs the improved n3correct aka N4correct
    //http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=5445030
    //Correction is done with a mask as per http://dx.doi.org/10.1016/j.neuroimage.2007.10.026
    //Winzorise intensity
    //Otsu mask, defrag, close the mask
    //Apply the mask to remove all background
    //Bestlinreg to mni space, use the MNI brain mask
    //Run N4 with the brain mask as a weighting and the otsu mask to rescale intensities at the end
    uses(GB:1.75) {
    exec """
    tmpdir=`mktemp -d` &&
    mincmath -clamp -const2 \$(mincstats -quiet -pctT 1 $input.mnc) \$(mincstats -quiet -pctT 95 $input.mnc) $input.mnc \$tmpdir/trunc.mnc &&
    mincmath -clamp -const2 \$(mincstats -quiet -pctT 1 $input.mnc) \$(mincstats -quiet -pctT 99 $input.mnc) $input.mnc \$tmpdir/trunc-final.mnc &&

    headmask \$tmpdir/trunc.mnc \$tmpdir/otsu.mnc &&
    mincdefrag \$tmpdir/otsu.mnc \$tmpdir/otsu_defrag.mnc 1 6 &&
    autocrop -isoexpand 50mm \$tmpdir/otsu_defrag.mnc \$tmpdir/otsu_expanded.mnc &&
    itk_morph --exp 'D[25] E[25]' \$tmpdir/otsu_expanded.mnc \$tmpdir/otsu_expanded_closed.mnc &&
    autocrop -from \$tmpdir/otsu_defrag.mnc \$tmpdir/otsu_expanded_closed.mnc \$tmpdir/otsu_closed.mnc &&

    minccalc -expression 'A[0]*A[1]' \$tmpdir/trunc.mnc \$tmpdir/otsu_closed.mnc \$tmpdir/masked.mnc &&
    minccalc -expression 'A[0]*A[1]'  \$tmpdir/trunc-final.mnc \$tmpdir/otsu_closed.mnc \$tmpdir/trunc-final_masked.mnc &&

    bestlinreg_g -nmi -lsq12 -sec_target ${REGISTRATIONMODEL2} \$tmpdir/masked.mnc ${REGISTRATIONMODEL} \$tmpdir/0.xfm &&

    itk_resample --clobber --invert_transform --labels --like \$tmpdir/trunc-final_masked.mnc --transform \$tmpdir/0.xfm ${REGISTRATIONBRAINMASK} \$tmpdir/weightmask.mnc &&

    N4BiasFieldCorrection -d 3 --verbose -r 1 -b [200] -c [200x200x200x200,0.0] -w \$tmpdir/weightmask.mnc -x \$tmpdir/otsu_closed.mnc -i \$tmpdir/trunc-final_masked.mnc -o $output.mnc &&
    rm -r \$tmpdir
    """
    }
}
```

**Comment by zichner** [comment]
Usually, line breaks within an `exec` block are ignored. Therefore, you need to use `;` or `&&` to separate commands. However, if you close the exec block with `""",false` instead of only `"""`, line breaks are kept, and thus, there is no need for `;` or `&&`.

**Comment by gdevenyi** [comment]
@zichner Is there a doc for the false thing somewhere?

I'm using ```""","n4correct"``` to name that exec block right now for resource manager purposes.

**Comment by ssadedin** [comment]
@gdevenyi  - it's undocumented but we should definitely add it.

Also, it should work to do:

```groovy
exec """
  my command
  another command
""",false,"someconfig"
```

This should get you the preserved line breaks and the config you want.

There's another thing worth mentioning: it won't eliminate line breaks when there are two in a row. So  you can also just write your commands spaced out:

```groovy
exec """
  my command

  another command
""","someconfig"
```

**Comment by gdevenyi** [comment]
Thanks @ssadedin 

Is this run as a true bash script? i.e. Could I add "set -e" at the beginning to make it bail out on errors? Can I use "#" to comment lines?

**Comment by ssadedin** [comment]
It will indeed run as a "true" bash script, although the form that takes
depends on the executor (eg: template used for SGE, etc.). By default all
scripts are executed with "set -e" included or using "bash -e" so that
should not be necessary on your part (again, this can vary by executor, but
the default for all of them should be to include it).

**Comment by gdevenyi** [comment]
Resolved.
