### ISSUE TITLE
bpipe doesn't allow empty branch list

### ISSUE THREAD

**Issue by supernifty** [ssadedin/bpipe#180]
We want to run different stages on different branches, conditional on a property of the input, i.e.:

```
samples_type_x * [ handle_x ],
samples_type_y * [ handle_y ]
```

However, this fails if samples_type_x or samples_type_y is empty, due to the requirement that sets must be non-empty, due to [PipelineCategory.groovy:221](https://github.com/ssadedin/bpipe/blob/42435dfcc102ec285f0e346cb51c8ec6dfc8ff7b/src/main/groovy/bpipe/PipelineCategory.groovy#L221). Could bpipe allow empty sets, to accommodate this situation?

**Comment by ssadedin** [comment]
I think we could probably relax that check. I put it in there because a few
users got confused when their pipelines appeared to silently not execute
because the input set was empty. Perhaps replace it to print out a mild
warning / message that the input set was empty?

**Comment by ssadedin** [comment]
Should now work with empty list (see regression test)
