### ISSUE TITLE
how to specify the hard queue list of Bpipe ?

### ISSUE THREAD

**Issue by WinterLi1993** [ssadedin/bpipe#189]
HI
   firstly ,I wrote a pipeline at a grooxy srcript . and  I use bpipe run to run this script ,but  I find that the status of this task always  'qw' . ( SGE installed in my server ) , I use 'qstat -j taskid' , I find these error information : 
   cannot run in queue "large.q" because it is not contained in its hard queue list (-q)
  So  how to set the hard queue list for Bpipe ???

**Comment by ssadedin** [comment]
Did you try using the queue setting in a bpipe.config file in the local directory? Eg.

```
queue="large.q"
```

**Comment by WinterLi1993** [comment]
ok,thanks!
