### ISSUE TITLE
bpipe-0.9.9.3 jobs started with bpipe-torque.sh aren't killed on pipeline shutdown

### ISSUE THREAD

**Issue by gdevenyi** [ssadedin/bpipe#199]
```
================================= Stage n4correct (OAS1_0001_MR1) ==================================
^C
Pipeline job running as process 20053.  Terminate? (y/n): y

Terminating process 20053 ...

Running stop command ...

The pipeline in this directory has already terminated

Cleaning up files from context .bpipe/inprogress/1
Cleaning up files from context .bpipe/inprogress/30
```

```
> jobinfo
40541561.gpc-sched-ib0   00:15:00   Q   1:ppn=8   n4correct
```

I think bpipe should be calling ``bpipe-torque.sh stop``?

**Comment by marchoeppner** [comment]
Same problem with SLURM. 
Works on: 0.9.9.b1
Fails on: 0.9.9b2, 0.9.9b3

I.e. the latest versions fail to shut down running jobs in the queue.

**Comment by ssadedin** [comment]
Thanks for raising this. I am doing some other work on the executors at the moment and will look at this at the same time.

**Comment by ssadedin** [comment]
This should be fixed in the latest master code. I will look at making a release soon to get this fix out.

Thank you again for raising it.
