### ISSUE TITLE
Bpipe configuration

### ISSUE THREAD

**Issue by Joeblack83** [ssadedin/bpipe#206]
Hi, 
I am trying to use bpipe and slurm to run my pipeline. 
I should include a specific option for slurm (--mem-per-cpu) in the Bpipe.config file but I do not know how.

Could you please help me?

Best,
Joe

**Comment by ssadedin** [comment]
Hi Joe,

Can you try setting the "custom_submit_options" value in your bpipe.config file? eg:

```
custom_submit_options="your option here"
```
