### ISSUE TITLE
any way to add third-party class definition?

### ISSUE THREAD

**Issue by hh1985** [ssadedin/bpipe#207]
Hi ssadedin,

I want to parse csv file in bpipe script. The csv contains sample and file information. The way that I am thinking of is to use groovycsv, which provides simple function like parseCsv(). But I have no idea of how to do it. The script simply reports error like java.lang.NoClassDefFoundError.  Any suggestions?

Thanks,

-hh1985

**Comment by ssadedin** [comment]
I see this isn't in the documentation, so thanks for raising it.

There are a few ways to get stuff into the classpath of your pipelines.

One is to make a folder called "bpipes" in your home directory and put a jar file in there called "extra-lib.jar". This was just an old workaround so it is kind of clunky but it does still work.

Now there is a more refined way: create a bpipe.config file next to your pipeline script, or in the directory you are running the pipeline in. You can then add in there a "libs" setting:

```
libs="/path/to/a/file.jar:/path/to/another/file.jar"
```

These jars will all get included at runtime.

There's even a third way which is neat if you want to distribute the pipeline script, but it doesn't quite work now out of the box. If you copy the file "ivy-2.4.0.jar " out of a normal Groovy installation into your Bpipe local-lib folder then you can use the native Groovy "Grape" mechanism to import libraries inside your pipeline script - eg:

```groovy
@Grapes(
  @Grab(group='com.xlson.groovycsv', module='groovycsv', version='1.1')
)       
import com.xlson.groovycsv.*
```
Hope this helps!

**Comment by hh1985** [comment]
Hi ssadedin,

Thanks a lot for the suggestion!  I will give them a try. This is very helpful because I am also considering passing an XML-like parameter file to bpipe specifying the program name and corresponding parameters.  Without the knowledge, I have to rewrite a xml parser:) 

-Han
