### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by PeteHaitch** [ssadedin/bpipe#208]
Hi Simon,

I hit some broken links while working through the very useful tutorial. E.g., on http://docs.bpipe.org/Tutorials/Hello,World/, the bottommost "Example With Inputs And Outputs" link resolves to http://docs.bpipe.org/Tutorials/Tutorials/ExampleWithInputsAndOutputs instead of http://docs.bpipe.org/Tutorials/ExampleWithInputsAndOutputs/ 

Cheers,
Pete

**Comment by ssadedin** [comment]
Thanks Pete!

Have fixed this in a commit that I'll push up soon.
