### ISSUE TITLE
mem_param is unset by default, breaking the torque submitter

### ISSUE THREAD

**Issue by TMiguelT** [ssadedin/bpipe#209]
Currently, if you run a bpipe pipeline with `executor="torque"`, and `mem_param` unset in `bpipe.config`, the job submission will fail, as bpipe will produce a PBS submission file with the line `#PBS -l =8gb` (because the $MEM_PARAM variable doesn't exist). This is an invalid job file, and thus the job will fail.

Is the solution to this, to set a default value for `mem_param` [here](https://github.com/ssadedin/bpipe/blob/db0eae4b360240fef754f1237152bfcf8928966f/src/main/groovy/bpipe/executor/CustomCommandExecutor.groovy#L235-L236)?

It seems that this was introduced in bpipe release 0.9.9.2, with the use of the `mem_param` config option: https://github.com/ssadedin/bpipe/blob/f76388446555e022dfcafbec3e91e2b714eeef7a/ReleaseNotes.txt#L49-L52

**Comment by ssadedin** [comment]
Thanks - this definitely looks like a bug. As you suggest, you can work around it by explicitly setting the `mem_param` to either "mem" or "pvmem" as suits your needs.

Will get this fix in to the next release (soon). It's worth noting there are a number of other fixes to the Torque executor that would be good for you to have as well - when I get to commit / merge it I will update this issue.

If you want to just apply the fixes, here is the patch:

```diff
diff --git a/bin/bpipe-torque.sh b/bin/bpipe-torque.sh
index 867fef9..a6c00bc 100755
--- a/bin/bpipe-torque.sh
+++ b/bin/bpipe-torque.sh
@@ -142,8 +142,9 @@ make_pbs_script () {

    # handle the batch and smp queues specially with regards to memory and procs
    case $QUEUE in
-      batch) if [[ -z $MEMORY ]]; then
-                : ${MEM_PARAM:=pvmem}
+      batch)
+             : ${MEM_PARAM:=pvmem}
+             if [[ -z $MEMORY ]]; then
                 memory_request="#PBS -l $MEM_PARAM=${DEFAULT_BATCH_MEM}gb"
              else
                 memory_request="#PBS -l $MEM_PARAM=${MEMORY}${MEM_UNIT}"
@@ -178,7 +179,7 @@ make_pbs_script () {
              ;;
    esac

-    mods_request = ""
+    mods_request=""
     #handle the module specifications. - Simon Gladman 2014
     if [[  ! -z $MODULES ]]; then
         for MOD in $MODULES
@@ -217,7 +218,7 @@ start () {
          # launch the job and get its id
          job_id_full=`qsub $CUSTOM_SUBMIT_OPTS $job_script_name`
          qsub_exit_status=$?
-         if [[ $? -eq 0 ]]
+         if [[ $qsub_exit_status -eq 0 ]]
             then
                # bite off the job number from the start of the job identifier
                job_id_number=`echo $job_id_full | sed -n 's/\([0-9][0-9]*\).*/\1/p'`
@@ -240,7 +241,7 @@ stop () {
          # try to stop it
          qdel "$1"
          qdel_success=$?
-         if [[ qdel_success == 0 ]]
+        if [[ $qdel_success == 0 ]]
             then
                exit $SUCCESS
             else
```

**Comment by TMiguelT** [comment]
Thanks! I'm happy to wait until the next release for the fix, since it's easy enough to work around for now
