### ISSUE TITLE
Any way to get the -n flag value?

### ISSUE THREAD

**Issue by hh1985** [ssadedin/bpipe#219]
Hi,

Is there any way to get the value of `-n` flag? The variable `threads` seems to be lazily determined. My situation is that I want to use SplitInterval from GATK4 to generate `n` sub intervals, so that MuTect2 can pick each of them and do the variant call job.  It's better to have the `n` equal to the value of `-n` flag.

-Han

**Comment by ssadedin** [comment]
Hi Han,

You can access the value directly in your pipeline using
bpipe.Config.config.maxThreads:

For example:

hello = {
    exec """
        echo "I have ${bpipe.Config.config.maxThreads} threads"
    """
}


Bpipe has some features to let you set it from within your script too:


hello = {
    uses(threads:8) {
        exec """
            echo "I have ${threads} threads"
        """
    }
}


So you can go either way - set it with -n, then pass that value to
SplitIntervals, or you can have a separate parameter and pass that to both
SplitIntervals and then the threads for command as well.

Hope this helps!

Simon

**Comment by hh1985** [comment]
Thank you so much:)
