### ISSUE TITLE
Reflection: stage name

### ISSUE THREAD

**Issue by hh1985** [ssadedin/bpipe#220]
Hi,

Just wonder if there is way to refer to the current stage name? For example,
hello = {
    println "I am in stage $stage"
}

The reason that I want this is to let the code extract parameters based on stage name.  In other words, the parameter for current stage will be dynamically generated from a parameter file (config.groovy, or json) 

Thanks,

-Han

**Comment by ssadedin** [comment]
You can do exactly that - the name of the current stage name is available as the `stageName` variable. So this should work:

```
hello = {
println "I am in stage $stageName"
}
```

**Comment by hh1985** [comment]
@ssadedin Interesting!  I didn't notice that:)  Thanks a lot!
