### ISSUE TITLE
Refer to output of certain stage

### ISSUE THREAD

**Issue by hh1985** [ssadedin/bpipe#228]
Hi,

Is it possible to refer back to the output of any given stage in the upstream? 

Thanks,

-Han

**Comment by gdevenyi** [comment]
I'm not aware of one, however you can construct the name of prior stages by doing something like this:
https://github.com/CobraLab/minc-bpipe-library/blob/master/minc-library.bpipe#L177

**Comment by hh1985** [comment]
@gdevenyi Great!  Thanks a lot!

**Comment by ssadedin** [comment]
Just to expand on @gdevenyi's answer with a few other options / thoughts:

In general, worth giving thought whether you really need to refer a specific stage's output as it makes your downstream stage less reusable. But there's plenty of situations where it can be a reasonable tradeoff.

One option that I frequently employ is branch variables, where you designate an output with a label which can be referred back to later on:

```groovy
hello = {
  exec "cp $input.txt $output.csv"

  branch.final_csv = output.csv
}

world = {
  from(final_csv) {
    exec "cp $input.csv $output.txt"
  }
}

run { hello + world }
```
This way you still get the output  you want, but you still have a lot of flexibility to put your stage into a different pipeline (as long is it too, specifies a "final_csv").
