### ISSUE TITLE
Cannot visit the website docs.bpipe.org

### ISSUE THREAD

**Issue by kexiao-seu** [ssadedin/bpipe#253]
There was a temporary DNS error.
Error Code: INET_E_RESOURCE_NOT_FOUND

**Comment by qrzhang** [comment]
Yes, I got the same problem. But I think you can  still find what you want directly from their github files  [https://github.com/ssadedin/bpipe/tree/master/docs](url)

**Comment by ssadedin** [comment]
closing as stale - bpipe docs are rehosted now on a different location with TLS/SSL.
