### ISSUE TITLE
How to run bpipe agent

### ISSUE THREAD

**Issue by desnar** [ssadedin/bpipe#254]
Hi,
I read the doc about JMS Integration in bpipe (http://docs.bpipe.org/Guides/JMS/),  and it said agent will run permanently in background and listen to the queue. But no more information about how to start agent.
I use the send command to send the command and these messages are shown in ActiveMQ webpage. But I'm not sure how to run the agent to get theses messages. I tried to run an inifinite loop groovy script with an agent config in same dir, but it seems not work.

**Comment by ssadedin** [comment]
Thanks for mentioning that - it's definitely an oversight that it isn't documented!

To run the agent, you use a command like so:

```
bpipe agent
```
Especially while testing I recommend giving it the `-v`  and `-n 1` arguments to turn on verbose mode (more logging) and limit the number of simultaneous messages it will process.

For example

```
bpipe agent -v -n 1
```

Hope this helps and thanks for mentioning it.

**Comment by desnar** [comment]
> Thanks for mentioning that - it's definitely an oversight that it isn't documented!
> 
> To run the agent, you use a command like so:
> 
> ```
> bpipe agent
> ```
> 
> Especially while testing I recommend giving it the `-v` and `-n 1` arguments to turn on verbose mode (more logging) and limit the number of simultaneous messages it will process to one at a time. Otherwise you can accidentally run a huge number of pipelines if something has filled up the queue in advance.
> 
> For example
> 
> ```
> bpipe agent -v -n 1
> ```
> 
> Hope this helps and thanks for mentioning it.

Thanks! It works well.
