### ISSUE TITLE
problem with running bpipe agent in multi concurrency

### ISSUE THREAD

**Issue by desnar** [ssadedin/bpipe#259]
Hi, 
    I'm trying to run bpipe in agent mode and receive queue info with activemq. I find that the bpipe log show scripts are executed but the scripts are not execued as exptected.  

The process that I run bpipe is as follows:    
  
The bpipe version is 0.9.9.7 and I build it from source.

I write a script to send commands to activemq, and the json is 
```py
        data= {
            "id": 0,
            "command":"run",
            "arguments":["-p", "idd=%d"%random.randint(1,1000000), "/home/user/test.groovy", ],
            "directory":"/home/user"
        }
```
I start the bpipe by command
```sh
bpipe run agent -v -n 10
``` 

the test.groovy script is 
```groovy
testModule = {exec"""touch /home/user/out/$idd  && echo $idd"""}
run { testModule }
``` 
I send the json data to amq 10 times at the same time, and the amq shows it in queue 10 messages, the bpipe server also show 10 times info about "Received command" / " Processing command" / "Command args are" / "Gained concurrency permit" / "Executing command". But the "Realeasing concurrency " info count and the count of file touched  are less than 10

For the amq out queue(bpipe responseQueue), I also cant see enough responses, and some messages contain info like "mv: cannot stat \u2018.bpipe/commandtmp/85/cmd.exit.tmp\u2019: No such file or directory\n"

After some tests, I find the result is wrong when concurrency(-n) is bigger than 1, and get worse if the  concurrency is bigger. This also happens in current master version bpipe

**Comment by ssadedin** [comment]
I'm not completely sure but I think you might be hitting the problem that you can't run two bpipe pipelines in the same directory at the same time.

It would probably be good if the agent recognised that and did not attempt to do that. But until / unless we implement that, it's up to you to make sure you don't run multiple pipelines in the same directory. If you want to have Bpipe create a unique directory, you can use the incrementing feature which is available in master where you specify the directory in the activemq message like

```json
{
    ...
    "directory" : "/home/user/bpipe_test_{inc}"
}
```

Bpipe will replace the `{inc}` part with an auto-incrementing number.

Can you check if this is the problem and let me know? if it's something else would definitely like to fix it!

**Comment by desnar** [comment]
> I'm not completely sure but I think you might be hitting the problem that you can't run two bpipe pipelines in the same directory at the same time.
> 
> It would probably be good if the agent recognised that and did not attempt to do that. But until / unless we implement that, it's up to you to make sure you don't run multiple pipelines in the same directory. If you want to have Bpipe create a unique directory, you can use the incrementing feature which is available in master where you specify the directory in the activemq message like
> 
> ```json
> {
>     ...
>     "directory" : "/home/user/bpipe_test_{inc}"
> }
> ```
> 
> Bpipe will replace the `{inc}` part with an auto-incrementing number.
> 
> Can you check if this is the problem and let me know? if it's something else would definitely like to fix it!

Thanks! Setting different bpipe running directories solve the problem.
