### ISSUE TITLE
Regression 0.9.9.6 -> 0.9.9.7 with waiting for files to appear in filesystem

### ISSUE THREAD

**Issue by gdevenyi** [ssadedin/bpipe#261]
With NFS filesystem and SGE jobs, there has been a regression from 0.9.9.6 -> 0.9.9.7 when waiting for files to appear.

Previously, files which take a short while to appear caused no issues, whereas now, even with fileSystemSyncTimeMs=500000 added to bpipe.config, the pipeline bails out while waiting for files to show up.

I don't see an item in the changelog referring to a change regarding this so I can't guess as to what did it.

**Comment by ssadedin** [comment]
Apologies for this problem. It's crept in with some significant refactoring to cloud-enable Bpipe (so Bpipe can now handle files living on S3, gcloud storage, etc as well as local files). In doing so a lot of the code that was checking file existence had to be ported to different APIs.

There are two fixes in master to address this - one of them (https://github.com/ssadedin/bpipe/commit/212291f755014893efcac799e1cde3c434695439) introduces `fileSystemSyncTimeMs` so unless you are building from master I think this wouldn't do anything yet.

Hoping to get a release out soon that has these fixes - am running them through our production pipelines for a bit to make sure they address the problem first though. But if you are willing to build from master and test on your end that would be super helpful!

**Comment by gdevenyi** [comment]
I can use 0.9.9.6 as its working fine. I just got caught out by this thinking some changes I made in the pipeline broke things.

**Comment by ssadedin** [comment]
Hi @gdevenyi , 0.9.9.8 was released last night and in our testing has resolved these issues. Let us know if you still experience any of them with that version - otherwise I'll close this out for now.
