### ISSUE TITLE
transform incorrectly processes directory names instead of filenames

### ISSUE THREAD

**Issue by gdevenyi** [ssadedin/bpipe#264]
I have the following stage
```
convert = {

  if(file(input).name.endsWith('.mnc')) {
      transform('.mnc') to('.convert.mnc') {
        exec """
            mincconvert -2 -clobber -compress 9 $input.mnc $output.mnc
        """
      }
  }
  else
  if(file(input).name.endsWith('.nii.gz')) {
      transform('.nii.gz') to('.convert.mnc') {
      exec """
          nii2mnc -clobber $input.nii.gz $output.mnc
      """
      }
  }
  else
  if(file(input).name.endsWith('.nii')) {
      transform('.nii') to('.convert.mnc') {
      exec """
          nii2mnc -clobber $input.nii $output.mnc
      """
      }
  }
  branch.nativemnc = "${branch.name}".minus(".mnc").minus(".nii.gz").minus(".nii").concat(".convert")
}
```

And if I feed it a file named like: `/maget/mnc_files/ndar_invmtj6urwd_20161130_132213_4d1_mri.mnc`, it invokes the following command for the convert stage:
```
mincconvert -2 -clobber -compress 9 /maget/mnc_files/ndar_invmtj6urwd_20161130_132213_4d1_mri.mnc maget.convert.mnc 
```

Somehow `$output.mnc` is getting getting populated by the base directory name. I suspect it has something to do with `mnc` being part of the directory tree name. Will have confirmation tomorrow that renaming the directory fixes this.

**Comment by gdevenyi** [comment]
Any feedback here? I have people getting bitten by this.

**Comment by gdevenyi** [comment]
Following up here has this been addressed?

**Comment by ssadedin** [comment]
Sorry for the lack of response / followup - tried this out and was able to create a reproducible test case from your code.

I will debug and see why it does that!  I assume there is something that is incorrectly matching the mnc within the directory path instead of the file name when doing the transform.

**Comment by ssadedin** [comment]
Added test & fix - the regression tests pass.  Would be great if you were able to build from source and confirm it fixes the problem at your end!
