### ISSUE TITLE
Modify preamble text when using shebang

### ISSUE THREAD

**Issue by lonsbio** [ssadedin/bpipe#266]
When using the shebang support in `bpipe`, i.e. scripts leading with:

```
#!/usr/bin/env bpipe
```

the first output line to the terminal is always `Stripping shebang` 

```
Stripping shebang
====================================================================================================
|                              Starting Pipeline at 2021-01-27 11:42                               |
====================================================================================================

```

Given the shebang can be used to present a `bpipe` script as a standalone program, the ability to either 

a) option to remove the `Stripping shebang`,and/or
b) add some custom text instead

would I think make it a bit of a nicer start to the terminal output and less confusing to a new user of the wrapped tool.

**Comment by ssadedin** [comment]
Thanks @lonsbio - agreed! I suspect it was never really intended to have it print that out, it was more a debug thing left in. So that is easy to remove.

For custom preamble I have toyed for a long while with making the [About](http://docs.bpipe.org/Language/About/)  `title` attribute be displayed instead of "Starting Pipeline ...", as well as using it as the banner when invalid arguments are supplied. Let me know any thoughts on that!

**Comment by ssadedin** [comment]
See 9d1f6274e300344f0ae33b667f3837e929280b80

**Comment by lonsbio** [comment]
Thanks @ssadedin , that looks great. `title` would be a good solution, customisable without too much overhead. 

Suppose the only other thing, which perhaps could be encapsulated in the `About` structure might be a  `subtitle` or `version` info so that there can something else there - again to try and replicate some kind of mimicry of a command line tool.

```
mytool
version 0.1.0
====================================================================================================
|                              Starting Pipeline at 2021-01-27 11:42                               |
====================================================================================================
```

**Comment by ssadedin** [comment]
closing for now as primary issue addressed, remaining features can be considered separately
