### ISSUE TITLE
LSF: handle jobs killed by resource limits

### ISSUE THREAD

**Issue by lonsbio** [ssadedin/bpipe#69]
_From [luquet...@gmail.com](https://code.google.com/u/100862348436398356765/) on 2013-01-23T02:07:50Z_

What steps will reproduce the problem? 1. Use the LSF executor
2. Submit to an LSF queue with a resource limit
3. Exceed the resource limit (e.g., CPU time) What is the expected output? What do you see instead? I expect the job to be killed by LSF and for bpipe to detect this and terminate the pipeline.  Instead, bpipe has no idea that the job has been killed and sits in a monitoring mode forever.  The reason this happens is because the "cmd.exit" file is never written when the job is killed due to resource over-usage. What version of the product are you using? On what operating system? bpipe-0.9.7
Linux flute000-178 3.2.0-0.bpo.2-amd64 #1 SMP Fri Jun 29 20:42:29 UTC 2012 x86_64 GNU/Linux Please provide any additional information below. When I first found this project, I was dismayed that the author chose to hack his own interface to resource schedulers like LSF and GridEngine.  The result is a system that works OK, but is not suitable for serious pipelines that take weeks to run.  Why was the choice made to *not* use a well-established, working library like DRMAA?

_Original issue: http://code.google.com/p/bpipe/issues/detail?id=69_

**Comment by ssadedin** [comment]
This should be addressed by https://github.com/ssadedin/bpipe/issues/168.

See the [lsf_array branch](https://github.com/ssadedin/bpipe/tree/lsf_array).
