### ISSUE TITLE
out of memory processing when operating on 500+ files

### ISSUE THREAD

**Issue by lonsbio** [ssadedin/bpipe#97]
_From [henning....@gmail.com](https://code.google.com/u/107754961382921025555/) on 2014-05-27T18:02:08Z_

Running a simple bpipe script like

get_quality = {
   exec """
   qc.pl -q -s 0 -i ${input} &&
   touch $output
   """
  forward input
}

summarise = {
  produce("summary.txt"){
    exec """
      summarize.py .
    """
  }
}

Bpipe.run {
  "&#37;" * [ get_quality ] + summarise
}

operating on 500+ files I get OutOfMemory exception even though I set 
: ${MAX_JAVA_MEM:="1024m"}
in bin/bpipe.

I know my example is poorly described, I just wanted to hear what you typically set MAX_JAVA_MEM too, if it is normal that bpipe requires a lot of memory like this?

...and btw, thanks for an awesome project we are getting more and more into bpipe here in my office!

_Original issue: http://code.google.com/p/bpipe/issues/detail?id=97_

**Comment by gdevenyi** [comment]
I'm up to setting MAX_JAVA_MEM to 12G to handle the following pipeline:
436 input files producing 16 ouput files via 8 pipeline stages.

It appears that there's a ton of memory usage tracking the existing output files, re-starting this pipeline after stopping it halfway through takes a ton of time on the file existence checking.

Implementation details here: https://github.com/CobraLab/minc-bpipe-library

**Comment by ssadedin** [comment]
That's a pretty small scale pipeline to run into this much memory trouble.

I did some optimisations of this already in the trunk in case you are not
running the latest build. Will have a look at your pipeline since it can
help me to see where the memory issues are coming from.

Cheers / thanks!

Simon

**Comment by gdevenyi** [comment]
I'm currently running 0.9.8.6 on:
```
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```

Do you think file sizes have any impact on this? Average filesize is 10-20Mb in this pipeline.

I'll grab a copy of the trunk and see if it exhibits similar behaviour.

**Comment by gdevenyi** [comment]
Sorry for another followup, looks like I need to build the git version, are there any build instructions around?

**Comment by gdevenyi** [comment]
Hrm, compile fails on java8, I wonder if it also has runtime issues, switching to java7 for testing.

**Comment by gdevenyi** [comment]
Built trunk on with java7, run with java7, with the default install (including memory 256)
```
Internal error: java.lang.OutOfMemoryError: Java heap space
Internal error: java.lang.OutOfMemoryError: GC overhead limit exceeded
Internal error: java.lang.OutOfMemoryError: Java heap space
Internal error: java.lang.OutOfMemoryError: Java heap space
Internal error: java.lang.OutOfMemoryError: GC overhead limit exceeded
Internal error: java.lang.OutOfMemoryError: Java heap space
Internal error: java.lang.OutOfMemoryError: GC overhead limit exceeded
Internal error: java.lang.OutOfMemoryError: GC overhead limit exceeded
Internal error: java.lang.OutOfMemoryError: GC overhead limit exceeded
Internal error: java.lang.OutOfMemoryError: GC overhead limit exceeded
Internal error: java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Thread-328" java.lang.OutOfMemoryError: Java heap space
Internal error: java.lang.OutOfMemoryError: Java heap space
Internal error: java.lang.OutOfMemoryError: Java heap space
Internal error: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by gdevenyi** [comment]
Any updates on the memory usage? I'm happy to test things.

**Comment by gdevenyi** [comment]
Hi, this is my yearly reminder than I can't run more than 200 inputs with bpipe without running out of ram on the control node.

**Comment by ssadedin** [comment]
I'm pleased to say that there has finally been significant work on this. I've just pushed up a branch ([liveoutputgraph](https://github.com/ssadedin/bpipe/tree/liveoutputgraph)) that has refactorings to remove all the major points that were consuming exponential memory as the number of inputs and outputs increase. A big part of that depends on the new java.nio APIs in Java7 so this branch is no longer compatible with JDK6. It would be great if you could test this out and report back any problems. I have been running it locally for quite a while now as a smoke test and I think it's working well. It's also significantly faster for large pipelines quite aside from the memory use.

**Comment by gdevenyi** [comment]
Wonderful!

I'll test tomorrow!

**Comment by gdevenyi** [comment]
I can make an initial report that my highly parallel multi input/output pipeline <https://github.com/CobraLab/minc-bpipe-library> now very quicky fires up and begins submitting jobs for 1000 input files without adjusting the memory (-Xmx256m) defaults.

Previously I had to up the allowable ram to 4G+ to run 300 input files.

Provided that this pipeline runs to completion without any memory issues, I consider this bug solved!

**Comment by gdevenyi** [comment]
Resuming seems to work, after running in #183 

I'd say my memory issues are solved!

**Comment by ssadedin** [comment]
That's great - thanks for testing. I'll give it a couple more weeks and then we can merge this into the main branch and move towards releasing it. It is a big internal refactoring so I will very much appreciate any careful scrutiny you can give it.

**Comment by gdevenyi** [comment]
Well, it's in production now for my lab, we have a ton of recently released large datasets that need processing

**Comment by gdevenyi** [comment]
Lots more testing and now use of 0.9.9.2, I'm pretty convinced that this bug is fixed. Hurrah!

**Comment by ssadedin** [comment]
Great to hear! Thanks so much for your persistence and patience. This was an important thing to fix.

**Comment by cfhammill** [comment]
I've run into the same problem as @gdevenyi on a PBS cluster using his minc-bpipe-library pipeline.

Running:
```
JAVA_MAX_MEM=10g bpipe run -n 400 $BPIPE ../t1s/recons/*.mnc &
```
and watching top shows vmem never getting higher than 6G, but I get

```
Internal error: java.lang.OutOfMemoryError: unable to create new native thread
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 120 bytes for AllocateHeap
[thread 46912529073920 also had an error]
[thread 46949354497792 also had an error]
```

```
java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by cfhammill** [comment]
I've run into the same problem as @gdevenyi on a PBS cluster using his minc-bpipe-library pipeline with bpipe 0.9.9.2

Running:
```
MAX_JAVA_MEM=12g bpipe run -n 400 $BPIPE ../t1s/recons/*.mnc &
```
and watching top shows VIRT balloons up to 17 gigs before dying, RES makes it to 700m or
so.

```
Internal error: java.lang.OutOfMemoryError: unable to create new native thread
=========================================== Bpipe Error ============================================

An error occurred executing your pipeline:

                                 unable to create new native thread                                 


Please see the details below for more information.

========================================== Error Details ===========================================

java.lang.OutOfMemoryError: unable to create new native thread
        at bpipe.Concurrency.execute(Concurrency.groovy:281)
        at bpipe.PipelineCategory.runAndWaitFor(PipelineCategory.groovy:553)
        at bpipe.PipelineCategory$runAndWaitFor$1.callStatic(Unknown Source)
        at bpipe.PipelineCategory.splitOnMap(PipelineCategory.groovy:539)
        at bpipe.PipelineCategory$_splitOnFiles_closure8.doCall(PipelineCategory.groovy:449)
        at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
        at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy:388)
        at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy)
        at bpipe.ParamsBinding.withLocalVariables(Runner.groovy:1001)
        at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy:387)
        at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy)
        at bpipe.PipelineStage.runBody(PipelineStage.groovy:375)
        at bpipe.PipelineStage.run(PipelineStage.groovy:248)
        at bpipe.Pipeline.runSegment(Pipeline.groovy:538)
        at bpipe.Pipeline.launchPipeline(Pipeline.groovy:661)
        at bpipe.Pipeline$_execute_closure7.doCall(Pipeline.groovy:636)
        at bpipe.Pipeline$_execute_closure7.doCall(Pipeline.groovy)
        at bpipe.Pipeline.execute(Pipeline.groovy:621)
        at bpipe.Pipeline.execute(Pipeline.groovy)
        at bpipe.Pipeline.run(Pipeline.groovy:499)
        at bpipe.Pipeline$run$0.callStatic(Unknown Source)
        at bpipe.Pipeline.run(Pipeline.groovy:459)
        at pipeline.bpipe.run(pipeline.bpipe.groovy:3)
        at pipeline.bpipe$run.call(Unknown Source)
        at bpipe.Runner.main(Runner.groovy:414)

```

```
java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by gdevenyi** [comment]
(coming in from off-list email with @cfhammill)

Maybe this is a PBS vs SGE thing, the cluster integration for PBS is old-style while SGE is new-style.

**Comment by ssadedin** [comment]
Hmm, I'm not sure about the virtual memory part, but when it says "unable to create new native thread" that suggests that it could be more a problem with having insufficient file handles than actual memory (Java throws OutOfMemory errors when it runs out of file handles). Might be worth checking if that's the issue or not. Some clusters enforce very low amount of file handles on the login node. You could try running Bpipe as an interactive job on a compute node just to see if it still gives you that error.

**Comment by cfhammill** [comment]
Hi Simon,

I think file handles aren't the issue - I'm starting bpipe from a login session, but the system limits are very permissive:

```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) 2097152
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 516274
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) 2097152
open files                      (-n) 32768
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 516274
virtual memory          (kbytes, -v) 20971520
file locks                      (-x) unlimited
```

So I'm thinking it is still the jvm hitting its memory limits
